<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>LADCoop</RootNamespace>
    <AssemblyName>Like a Dragon Co-op</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Platforms>AnyCPU;x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <None Include="App.config" />
    <!-- keep packages.config for now to avoid changing package restore behavior until packages are migrated -->
    <None Include="packages.config" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MinHook.NET" Version="1.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Y7Internal.NET\DELibrary.NET\DELibrary.NET.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LibARMP">
      <HintPath>LibARMP.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
